# pylint: disable=line-too-long
# pylint: disable=missing-module-docstring

FONTS = [
    {
        "name": "Dangerous Seed",
        "file": "SEED.png",
        "output": "SEED.json",
    }, {
        "name": "Dangerous Seed Monospaced",
        "file": "SEED.png",
        "output": "SEED Mono.json",
        "monospace": True,
        "finetune": {
            ",": (0, 1)
        }
    },

    {"name": "7 Custom", "file": "7.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "7.json"},
    {"name": "7MOD", "file": "7MOD.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "7MOD.json"},
    {"name": "1943", "file": "1943.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "1943.json"},
    {"name": "2048 Custom", "file": "2048.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "2048.json"},
    {"name": "AAZ", "file": "AAZ.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "AAZ.json"},
    {"name": "acro-lower", "file": "acro-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "acro-lower.json"},
    {"name": "Aero Fighters", "file": "AERO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "AERO.json"},
    {"name": "Afterburner", "file": "AFTR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "AFTR.json"},
    {"name": "ALKI", "file": "ALKI.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ALKI.json"},
    {"name": "Art of Fighting 2 (SNK)", "file": "aof2.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "aof2.json"},
    {"name": "Arabian Magic (Capcom)", "file": "arab.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "arab.json"},
    {"name": "arab-lower", "file": "arab-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "arab-lower.json"},
    {"name": "armo-lower", "file": "armo-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "armo-lower.json"},
    {"name": "ARTDECO", "file": "ARTDECO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ARTDECO.json"},
    {"name": "ass-lower", "file": "ass-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ass-lower.json"},
    {"name": "Assault (Namco)", "file": "assault.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "assault.json"},
    {"name": "Asterix (Konami)", "file": "astx.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "astx.json"},
    {"name": "ATASCII", "file": "atascii.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "atascii.json"},
    {"name": "atascii-lower", "file": "atascii-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "atascii-lower.json"},
    {"name": "Aurail (Sega)", "file": "aura.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "aura.json"},
    {"name": "Avengers (Capcom)", "file": "avng.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "avng.json"},
    {"name": "Battle Bakraid (Eighting)", "file": "bakr.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "bakr.json"},
    {"name": "bakr-lower", "file": "bakr-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "bakr-lower.json"},
    {"name": "Batsugun (Toaplan)", "file": "bats.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "bats.json"},
    {"name": "Bay Route (Sega)", "file": "bayr.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "bayr.json"},
    {"name": "bayr-lower", "file": "bayr-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "bayr-lower.json"},
    {"name": "BattleCircuit (Capcom)", "file": "bcir.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "bcir.json"},
    {"name": "bcir-lower", "file": "bcir-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "bcir-lower.json"},
    {"name": "bdash", "file": "bdash.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "bdash.json"},
    {"name": "bdash-lower", "file": "bdash-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "bdash-lower.json"},
    {"name": "Black Tiger (Capcom)", "file": "blkt.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "blkt.json"},
    {"name": "BLSD (Better LittleSound DJ)", "file": "BLSD.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "BLSD.json"},
    {"name": "Blood Warrior (Kaneko)", "file": "blwa.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "blwa.json"},
    {"name": "BOLD", "file": "BOLD.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "BOLD.json"},
    {"name": "Bonanza Bros (Sega)", "file": "bonz.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "bonz.json"},
    {"name": "Boogie Wings (Data East)", "file": "boog.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "boog.json"},
    {"name": "boog-lower", "file": "boog-lower.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "boog-lower.json"},
    {"name": "BOOM", "file": "BOOM.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "BOOM.json"},
    {"name": "BUBL", "file": "BUBL.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "BUBL.json"},
    {"name": "C64 Custom", "file": "C64.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "C64.json"},
    {"name": "C64M", "file": "C64M.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "C64M.json"},
    {"name": "Castlevania 3", "file": "Castlevania3.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "Castlevania3.json"},
    {"name": "Chiki Chiki Boys (Capcom)", "file": "chiki.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "chiki.json"},
    {"name": "CHROME", "file": "CHROME.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "CHROME.json"},
    {"name": "CIRC", "file": "CIRC.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "CIRC.json"},
    {"name": "Cliffhanger - Edward Randy (DataEast)", "file": "cliff.png", "offset_row": 4, "offset_col": 6,
     "scale": 1, "letter_space": 64, "copy": "Copyright (c) 2025", "output": "cliff.json"},
    {"name": "Commando-Special (Capcom)", "file": "cmnds.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "cmnds.json"},
    {"name": "COOL", "file": "COOL.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "COOL.json"},
    {"name": "Captain Sky Hawk (RARE)", "file": "cshk.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "cshk.json"},
    {"name": "DoDonPachi (Cave)", "file": "ddp.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ddp.json"},
    {"name": "Dance Dance Revolution (Konami)", "file": "DDR.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "DDR.json"},
    {"name": "DEFF", "file": "DEFF.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "DEFF.json"},
    {"name": "Detana Twinbee (Konami)", "file": "deta.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "deta.json"},
    {"name": "Digi 5x5", "file": "Digi 5x5.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "Digi 5x5.json"},
    {"name": "Dimahoo (Raizing)", "file": "dima.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "dima.json"},
    {"name": "DOSmod", "file": "DOSmod.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "DOSmod.json"},
    {"name": "DOS Uppercase Custom", "file": "DOSU.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "DOSU.json"},
    {"name": "Delta Ray from Wipeout 3", "file": "DRAY.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "DRAY.json"},
    {"name": "Dragon Breed (Irem)", "file": "drbr.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "drbr.json"},
    {"name": "Dragon Spirit (Namco)", "file": "dspir.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "dspir.json"},
    {"name": "Dual", "file": "Dual.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "Dual.json"},
    {"name": "DUMB", "file": "DUMB.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "DUMB.json"},
    {"name": "Dynamite Dux (slight mod)", "file": "DUX.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "DUX.json"},
    {"name": "Earthbound", "file": "Earthbound.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "Earthbound.json"},
    {"name": "EarthboundZero", "file": "EarthboundZero.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "EarthboundZero.json"},
    {"name": "ESCH", "file": "ESCH.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ESCH.json"},
    {"name": "F1 Dream (Capcom)", "file": "f1dr.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "f1dr.json"},
    {"name": "FARX", "file": "FARX.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "FARX.json"},
    {"name": "Flak Attack", "file": "FLAK.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "FLAK.json"},
    {"name": "Flixel", "file": "FLXL.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "FLXL.json"},
    {"name": "Flying Shark (Taito)", "file": "flys.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "flys.json"},
    {"name": "Fantasy Zone (Sega)", "file": "fz.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "fz.json"},
    {"name": "gaia", "file": "gaia.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "gaia.json"},
    {"name": "Gain Ground (Sega)", "file": "gain.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "gain.json"},
    {"name": "Garou Densetsu (SNK)", "file": "garou.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "garou.json"},
    {"name": "Metal Gear", "file": "GEAR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "GEAR.json"},
    {"name": "Ghosts n Goblins (Capcom)", "file": "gng1.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "gng1.json"},
    {"name": "Ghouls n Ghosts (Capcom)", "file": "gng2.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "gng2.json"},
    {"name": "Gradius 2", "file": "GRD2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "GRD2.json"},
    {"name": "Gradius 3", "file": "GRD3.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "GRD3.json"},
    {"name": "Gradius 4", "file": "GRD4.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "GRD4.json"},
    {"name": "GunNail (NMK)", "file": "gunn.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "gunn.json"},
    {"name": "Gun.Smoke (Capcom)", "file": "guns.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "guns.json"},
    {"name": "Hacha Mecha Fighter (NMK)", "file": "hach.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "hach.json"},
    {"name": "Hand", "file": "Hand.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "Hand.json"},
    {"name": "Hat Trick Hero 95 (Taito)", "file": "hatt.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "hatt.json"},
    {"name": "IBM Console", "file": "IBMC.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "IBMC.json"},
    {"name": "Image Fight (IREM)", "file": "imgf.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "imgf.json"},
    {"name": "K subs", "file": "K subs.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "K subs.json"},
    {"name": "K sup", "file": "K sup.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "K sup.json"},
    {"name": "Kaiser Knuckle (Taito)", "file": "kais.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "kais.json"},
    {"name": "Ketsui (Cave)", "file": "KETSUI.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "KETSUI.json"},
    {"name": "Kiki Kaikai (Taito)", "file": "kiki.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "kiki.json"},
    {"name": "KIKOplus", "file": "KIKOplus.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "KIKOplus.json"},
    {"name": "Kirameki Star Road (Taito)", "file": "kira.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "kira.json"},
    {"name": "Kirby's Dreamland 2 (HAL)", "file": "Kirby's Dreamland 2 (HAL).png", "offset_row": 4, "offset_col": 6,
     "scale": 1, "letter_space": 64, "copy": "Copyright (c) 2025", "output": "Kirby's Dreamland 2 (HAL).json"},
    {"name": "KLAX", "file": "KLAX.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "KLAX.json"},
    {"name": "King of Fighters 2000 (SNK)", "file": "KoF2k.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "KoF2k.json"},
    {"name": "King of Fighters 2001 (SNK)", "file": "KoF2k1.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "KoF2k1.json"},
    {"name": "King of Fighters 97 (SNK)", "file": "kof97.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "kof97.json"},
    {"name": "Konami NES", "file": "KonamiNES.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "KonamiNES.json"},
    {"name": "KRYZ", "file": "KRYZ.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "KRYZ.json"},
    {"name": "Last Resort (SNK)", "file": "last.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "last.json"},
    {"name": "LCD", "file": "LCD.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "LCD.json"},
    {"name": "LITR", "file": "LITR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "LITR.json"},
    {"name": "Litro Lowercase", "file": "LTRL.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "LTRL.json"},
    {"name": "Litro Uppercase", "file": "LTRU.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "LTRU.json"},
    {"name": "lwing", "file": "lwing.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "lwing.json"},
    {"name": "Lizard NES", "file": "LZRD.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "LZRD.json"},
    {"name": "M9MF", "file": "M9MF.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "M9MF.json"},
    {"name": "Mars Matrix (Capcom)", "file": "mars.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "mars.json"},
    {"name": "MECH", "file": "mech.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "mech.json"},
    {"name": "Virt", "file": "microd-virt-contrast.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "microd-virt-contrast.json"},
    {"name": "mjack", "file": "mjack.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "mjack.json"},
    {"name": "moma", "file": "moma.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "moma.json"},
    {"name": "monl", "file": "monl.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "monl.json"},
    {"name": "Monofur", "file": "MONO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "MONO.json"},
    {"name": "Monofur Caps (No aliasing)", "file": "monofur-caps-noalias.png", "offset_row": 4, "offset_col": 6,
     "scale": 1, "letter_space": 64, "copy": "Copyright (c) 2025", "output": "monofur-caps-noalias.json"},
    {"name": "Monofur (No aliasing)", "file": "monofur-noalias.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "monofur-noalias.json"},
    {"name": "monu", "file": "monu.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "monu.json"},
    {"name": "Mario Bros", "file": "MRIO1.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "MRIO1.json"},
    {"name": "MRIO", "file": "MRIO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "MRIO.json"},
    {"name": "mt", "file": "mt.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "mt.json"},
    {"name": "muni", "file": "muni.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "muni.json"},
    {"name": "mwar", "file": "mwar.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "mwar.json"},
    {"name": "namco2", "file": "namco2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "namco2.json"},
    {"name": "nebu", "file": "nebu.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "nebu.json"},
    {"name": "NEO", "file": "NEO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "NEO.json"},
    {"name": "NEScape! (slight mod)", "file": "nescape.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "nescape.json"},
    {"name": "New York Times", "file": "New York Times.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "New York Times.json"},
    {"name": "NICE", "file": "NICE.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "NICE.json"},
    {"name": "NIMA", "file": "NIMA.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "NIMA.json"},
    {"name": "ninj", "file": "ninj.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ninj.json"},
    {"name": "ninja", "file": "ninja.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ninja.json"},
    {"name": "ninjas", "file": "ninjas.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ninjas.json"},
    {"name": "NOSHADE", "file": "NOSHADE.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "NOSHADE.json"},
    {"name": "NUM", "file": "NUM.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "NUM.json"},
    {"name": "OPTC", "file": "OPTC.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "OPTC.json"},
    {"name": "ord", "file": "ord.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ord.json"},
    {"name": "outf", "file": "outf.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "outf.json"},
    {"name": "OUTLINE", "file": "OUTLINE.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "OUTLINE.json"},
    {"name": "pabom", "file": "pabom.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "pabom.json"},
    {"name": "paro", "file": "paro.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "paro.json"},
    {"name": "PCB Artist", "file": "PCB.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "PCB.json"},
    {"name": "pckf", "file": "pckf.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "pckf.json"},
    {"name": "PICO8", "file": "pico.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "pico.json"},
    {"name": "PICO8 lowercase", "file": "pico-small.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "pico-small.json"},
    {"name": "Pokémon 7x7 Bold", "file": "PKBD.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "PKBD.json"},
    {"name": "Pokémon 6x7", "file": "PKMN.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "PKMN.json"},
    {"name": "Pokémon 7x7", "file": "PKRE.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "PKRE.json"},
    {"name": "PROT", "file": "PROT.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "PROT.json"},
    {"name": "psr2", "file": "psr2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "psr2.json"},
    {"name": "ptx", "file": "ptx.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ptx.json"},
    {"name": "pubu", "file": "pubu.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "pubu.json"},
    {"name": "puls", "file": "puls.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "puls.json"},
    {"name": "quake", "file": "quake.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "quake.json"},
    {"name": "raph", "file": "raph.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "raph.json"},
    {"name": "rayf", "file": "rayf.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "rayf.json"},
    {"name": "RED", "file": "RED.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "RED.json"},
    {"name": "Renoise", "file": "Renoise.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "Renoise.json"},
    {"name": "rf", "file": "rf.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "rf.json"},
    {"name": "robot", "file": "robot.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "robot.json"},
    {"name": "rtl", "file": "rtl.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "rtl.json"},
    {"name": "rtype", "file": "rtype.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "rtype.json"},
    {"name": "rumba", "file": "rumba.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "rumba.json"},
    {"name": "RVN", "file": "RVN.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "RVN.json"},
    {"name": "sabo", "file": "sabo.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sabo.json"},
    {"name": "sala2", "file": "sala2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sala2.json"},
    {"name": "samsho2", "file": "samsho2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "samsho2.json"},
    {"name": "samsho3", "file": "samsho3.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "samsho3.json"},
    {"name": "SAR", "file": "SAR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SAR.json"},
    {"name": "sboom", "file": "sboom.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sboom.json"},
    {"name": "sdi", "file": "sdi.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sdi.json"},

    {"name": "sf2", "file": "sf2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sf2.json"},
    {"name": "sfz3", "file": "sfz3.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "sfz3.json"},
    {"name": "Sgt. Helmet Training Day", "file": "SGT.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "SGT.json"},
    {"name": "SHADED", "file": "SHADED.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SHADED.json"},
    {"name": "shda", "file": "shda.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "shda.json"},
    {"name": "shinobi", "file": "shinobi.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "shinobi.json"},
    {"name": "Simpsons", "file": "SIMP.png", "offset_row": 5, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SIMP.json"},
    {"name": "skyfox", "file": "skyfox.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "skyfox.json"},
    {"name": "skys", "file": "skys.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "skys.json"},
    {"name": "Super Mario Bros 3 Lowercase", "file": "SM3L.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "SM3L.json"},
    {"name": "Super Mario Bros 3 Uppercase", "file": "SM3U.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "SM3U.json"},
    {"name": "SMOL", "file": "SMOL.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SMOL.json"},
    {"name": "snow", "file": "snow.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "snow.json"},
    {"name": "solo", "file": "solo.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "solo.json"},
    {"name": "Sonic Robo Blast 2 Console Custom", "file": "Sonic Robo Blast 2 Console.png", "offset_row": 4,
     "offset_col": 6, "scale": 1, "letter_space": 64, "copy": "Copyright (c) 2025",
     "output": "Sonic Robo Blast 2 Console.json"},
    {"name": "spdr", "file": "spdr.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "spdr.json"},
    {"name": "SQUA", "file": "SQUA.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SQUA.json"},
    {"name": "SQui", "file": "SQui.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "SQui.json"},
    {"name": "ssf2", "file": "ssf2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ssf2.json"},
    {"name": "Blazing Star", "file": "STAR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "STAR.json"},
    {"name": "STR2", "file": "STR2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "STR2.json"},
    {"name": "Strider", "file": "STRI.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "STRI.json"},
    {"name": "tataka", "file": "tataka.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "tataka.json"},
    {"name": "Terminus Lowercase Custom", "file": "TERM.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "TERM.json"},
    {"name": "Terminal 42", "file": "Terminal 42.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "Terminal 42.json"},
    {"name": "terra", "file": "terra.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "terra.json"},
    {"name": "Tetris", "file": "tetris.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "tetris.json"},
    {"name": "thdr", "file": "thdr.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "thdr.json"},
    {"name": "times", "file": "times.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "times.json"},
    {"name": "Times New Roman", "file": "Times New Roman.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64, "copy": "Copyright (c) 2025", "output": "Times New Roman.json"},
    {"name": "tp84", "file": "tp84.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "tp84.json"},
    {"name": "Trash80", "file": "TR80.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "TR80.json"},
    {"name": "Tracker Wide Custom", "file": "TRAK.png", "offset_row": 4, "offset_col": 6, "scale": 1,
     "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "TRAK.json"},
    {"name": "Tetris2", "file": "TRIS.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "TRIS.json"},
    {"name": "trs", "file": "trs.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "trs.json"},
    {"name": "trx", "file": "trx.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "trx.json"},
    {"name": "Twinbee", "file": "twin.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "twin.json"},
    {"name": "twin2", "file": "twin2.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "twin2.json"},
    {"name": "Twin Cobra", "file": "twincobra.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "twincobra.json"},
    {"name": "Twin Qix", "file": "twinqix.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "twinqix.json"},
    {"name": "twq", "file": "twq.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "twq.json"},
    {"name": "typh", "file": "typh.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "typh.json"},
    {"name": "unsq", "file": "unsq.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "unsq.json"},
    {"name": "vict", "file": "vict.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "vict.json"},
    {"name": "waku", "file": "waku.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "waku.json"},
    {"name": "wboy", "file": "wboy.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "wboy.json"},
    {"name": "Wild Pilot", "file": "wildpilot.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "wildpilot.json"},
    {"name": "will", "file": "will.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "will.json"},
    {"name": "xain", "file": "xain.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "xain.json"},
    {"name": "xexex", "file": "xexex.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "xexex.json"},
    {"name": "ZEPHYR", "file": "ZEPHYR.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ZEPHYR.json"},
    {"name": "Zero Wing", "file": "ZERO.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ZERO.json"},
    {"name": "ZERO 6x7", "file": "ZERO6.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ZERO6.json"},
    {"name": "ZERO6mod", "file": "ZERO6mod.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ZERO6mod.json"},
    {"name": "ZEROmod", "file": "ZEROmod.png", "offset_row": 4, "offset_col": 6, "scale": 1, "letter_space": 64,
     "copy": "Copyright (c) 2025", "output": "ZEROmod.json"},
    {"name": "ZERO 2", "file": "ZEROmod2.png", "offset_row": 4,
     "offset_col": 6, "scale": 1, "letter_space": 64, "copy": "Copyright (c) 2025", "output": "ZEROmod2.json"}
]
